# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 404)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 501, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.browserRP = QtWidgets.QTextBrowser(self.tab_3)
        self.browserRP.setGeometry(QtCore.QRect(20, 140, 451, 181))
        self.browserRP.setObjectName("browserRP")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.okButtonRP = QtWidgets.QPushButton(self.tab_3)
        self.okButtonRP.setGeometry(QtCore.QRect(390, 100, 81, 31))
        self.okButtonRP.setObjectName("okButtonRP")
        self.lineEditNewRP = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditNewRP.setGeometry(QtCore.QRect(90, 100, 291, 31))
        self.lineEditNewRP.setObjectName("lineEditNewRP")
        self.chooseButtonRP = QtWidgets.QToolButton(self.tab_3)
        self.chooseButtonRP.setGeometry(QtCore.QRect(390, 20, 81, 31))
        self.chooseButtonRP.setObjectName("chooseButtonRP")
        self.lineEditPathRP = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditPathRP.setGeometry(QtCore.QRect(90, 20, 291, 31))
        self.lineEditPathRP.setObjectName("lineEditPathRP")
        self.lineEditOldRP = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditOldRP.setGeometry(QtCore.QRect(90, 60, 291, 31))
        self.lineEditOldRP.setObjectName("lineEditOldRP")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.okButtonRN = QtWidgets.QPushButton(self.tab_4)
        self.okButtonRN.setGeometry(QtCore.QRect(390, 60, 81, 31))
        self.okButtonRN.setObjectName("okButtonRN")
        self.lineEditNewRN = QtWidgets.QLineEdit(self.tab_4)
        self.lineEditNewRN.setGeometry(QtCore.QRect(90, 60, 291, 31))
        self.lineEditNewRN.setObjectName("lineEditNewRN")
        self.lineEditPathRN = QtWidgets.QLineEdit(self.tab_4)
        self.lineEditPathRN.setGeometry(QtCore.QRect(90, 20, 291, 31))
        self.lineEditPathRN.setObjectName("lineEditPathRN")
        self.chooseButtonRN = QtWidgets.QToolButton(self.tab_4)
        self.chooseButtonRN.setGeometry(QtCore.QRect(390, 20, 81, 31))
        self.chooseButtonRN.setObjectName("chooseButtonRN")
        self.browserRN = QtWidgets.QTextBrowser(self.tab_4)
        self.browserRN.setGeometry(QtCore.QRect(20, 140, 451, 181))
        self.browserRN.setObjectName("browserRN")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "新名稱 :"))
        self.label_2.setText(_translate("Dialog", "舊名稱 :"))
        self.label.setText(_translate("Dialog", "路徑 :"))
        self.okButtonRP.setText(_translate("Dialog", "更改名稱"))
        self.chooseButtonRP.setText(_translate("Dialog", "選擇路徑"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "RP"))
        self.label_4.setText(_translate("Dialog", "新名稱 :"))
        self.label_6.setText(_translate("Dialog", "路徑 :"))
        self.okButtonRN.setText(_translate("Dialog", "更改名稱"))
        self.chooseButtonRN.setText(_translate("Dialog", "選擇路徑"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "RN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
